Shop/Web/Models/Purchase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseItems = new HashSet<PurchaseItems>();
        }
    
        public int Id { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal PaidAmount { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }
    }
}

Shop/Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class CommonController : Controller
    {
        private ShopDb_Hassanuzzaman_01735807216Entities db = new ShopDb_Hassanuzzaman_01735807216Entities();

        public JsonResult getPhonenumber(string term)
        {


            var phonenumber = db.Customer.Where(x => x.Phone.StartsWith(term)).Select(s => s.Phone).Take(5).ToList();

            return Json(phonenumber, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getPhonenumberSupplier(string term)
        {


            var phonenumber = db.Supplier.Where(x => x.Phone.StartsWith(term)).Select(s => s.Phone).Take(5).ToList();

            return Json(phonenumber, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductSalesPrice(int id)
        {
            var data = db.Product.Where(x => x.Id == id).Select(y => y.SalesPrice).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductPurchasePrice(int id)
        {
            var data = db.Product.Where(x => x.Id == id).Select(y => y.PurchasePrice).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        
        public JsonResult GetCustomer(string id)
        {

            var data = db.Customer.Where(x => x.Phone == id).Select(y => new {  Name = y.Name }).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSupplier(string id)
        {

            var data = db.Supplier.Where(x => x.Phone == id).Select(y => new { Name = y.Name }).FirstOrDefault();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCustomerOrder(string id)
        {
            var customer = db.Customer.FirstOrDefault(x => x.Phone == id);
            List<SelectListItem> OrderList = new List<SelectListItem>();
            if (customer != null)
            {
                var order = db.Sales.Where(x => x.CustomerId == customer.Id).ToList();
                foreach (var item in order)
                {
                    OrderList.Add(new SelectListItem { Text = item.Id.ToString(), Value = item.Id.ToString() });
                }
            }

            return Json(OrderList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSupplierOrder(string id)
        {
            var supplier = db.Supplier.FirstOrDefault(x => x.Phone == id);
            List<SelectListItem> OrderList = new List<SelectListItem>();
            if (supplier != null)
            {
                var order = db.Purchase.Where(x => x.SupplierId == supplier.Id).ToList();
                foreach (var item in order)
                {
                    OrderList.Add(new SelectListItem { Text = item.Id.ToString(), Value = item.Id.ToString() });
                }
            }

            return Json(OrderList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GraphData()
        {
            var date = DateTime.Now;
            var salesData = db.Sales.Where(x => x.SalesDate.Year == date.Year).ToList();
            List<string[]> orderObj = new List<string[]>();
            foreach(var item in salesData.GroupBy(g=>g.SalesDate))
            {
                var res= "gd(" + item.Key.Year + "," + item.Key.Month + "," + item.Key.Day + ")," + item.Select(s => s.TotalAmount).Sum();
                orderObj.Add(new string[] { res});
            }



            //var data = db.Sales
            //    .Where(x => x.SalesDate.Year == date.Year).
            //    GroupBy(g => g.SalesDate.Month)
            //    .Select(s => new { Month = s.Key, No = s.Count() }).ToList();

            //var ret = new[]
            //{
            //new { label="Sales", data = data.Select(x=>new int[]{ x.Month, x.No }),color="#000"},

            //};

            var ret = new[] { new {orderData=orderObj } };
            return Json(ret, JsonRequestBehavior.AllowGet);
        }
    }
}

Shop/Web/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class PurchaseController : Controller
    {
        private ShopDb_Hassanuzzaman_01735807216Entities db = new ShopDb_Hassanuzzaman_01735807216Entities();
        public ActionResult Index()
        {
            return View(db.Purchase.Include("PurchaseItems").ToList());
        }

        public ActionResult Create()
        {
            ViewBag.Date = DateTime.Now.ToString("dd/MM/yyyy");
            ViewBag.Product = new SelectList(db.Product.ToList(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(string SupplierPhone, string SupplierName, decimal Discount, DateTime Date, List<int> productId, List<decimal> productPrice, List<decimal> productTotalPrice, List<int> productQty, decimal TotalBill, decimal NetReceivable, decimal Payment, decimal Change)
        {

            try
            {
                var SupplierData = db.Supplier.Where(x => x.Phone == SupplierPhone).FirstOrDefault();
                if (SupplierData == null)
                {
                    Supplier person = new Supplier();
                    person.Name = SupplierName;
                    person.Phone = SupplierPhone;
                    db.Supplier.Add(person);
                    db.SaveChanges();
                    SupplierData = person;
                }
                decimal paidAmount = Payment - Change;
                var dt = new DataTable();
                dt.Columns.Add("ProductId");
                dt.Columns.Add("QTY");
                dt.Columns.Add("Price");


                // collect order items.... 
                for (int j = 0; j < productId.Count(); j++)
                {
                    var PriceRate = productPrice[j];
                    var Product_Id = productId[j];
                    int QTY = productQty[j];
                    dt.Rows.Add(Product_Id, QTY, PriceRate);
                }

                //save product order
                SqlParameter _date = new SqlParameter("@date", Date);
                SqlParameter _supplierId = new SqlParameter("@supplierId", SupplierData.Id);
                SqlParameter _totalAmount = new SqlParameter("@totalAmount", TotalBill);
                SqlParameter _discount = new SqlParameter("@discount", Discount);
                SqlParameter _paidAmount = new SqlParameter("@paidAmount", paidAmount);
                SqlParameter _itemList = new SqlParameter("@itemList", SqlDbType.Structured);
                _itemList.Value = dt;
                _itemList.TypeName = "PURCHASEITEMTYPE";
                db.Database.ExecuteSqlCommand("spSavePurchase @date,@SupplierId,@totalAmount,@discount,@paidAmount,@itemList", _date, _supplierId, _totalAmount, _discount, _paidAmount, _itemList);

            }
            catch (Exception ex)
            {
                return View("Create");
            }



            return RedirectToAction("Index");
        }
    }
}

Shop/Web/Views/Purchase/Create.cshtml
<style>
    .borderlessText {
        background-color: transparent;
        border: 0px solid;
        height: 20px;
        width: 160px;
        color: #ff6a00;
        font-weight: bold;
        font-size: 16px;
        text-align: right;
    }

    *:focus {
        outline: none;
    }
</style>



<div class="wrapper wrapper-content animated fadeInRight">
    @using (Html.BeginForm("Create", "Purchase", FormMethod.Post, new { id = "SubmitForm" }))
    {
        <div class="row">
            <div class="col-lg-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Supplier</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="form-group"><label>Phone</label>  @Html.TextBox("SupplierPhone", null, new { @class = "form-control autoPhone" })</div>
                                <div class="form-group"><label>Name</label> @Html.TextBox("SupplierName", null, new { @class = "form-control " }) </div>
                                <ul class="nav nav-stacked" id="OrderList"></ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Purchase...</h5>
                        <div class="ibox-tools pull-right">
                            @Html.TextBox("Date", null, new { @class = "borderlessText date", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="ibox-content">
                        <p>Select product and add to basket list.</p>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group form-inline">
                                    @Html.Label("Product")
                                    @Html.DropDownList("Product", null, "--Select--", new { @class = "selectpicker", @style = "width:150px;" })
                                    @Html.Label("Quantity")
                                    @Html.TextBox("Quantity", null, new { @autocomplete = "off", @class = "number", @style = "width:50px;text-align:center;", @Value = "1" })
                                    @Html.Label("Price")
                                    @Html.TextBox("Price", null, new { @type = "number", @style = "width:70px;text-align:center;", @readonly = "readonly" })
                                    @Html.Label("Total Price")
                                    @Html.TextBox("TotalPrice", null, new { @readonly = "readonly", @style = "width:80px;text-align:center;" })
                                    <button type="button" id="addItem" class="btn btn-xs btn-info"><i class="fa fa-cart-plus"></i>  Add to Cart</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table id="ItemTable" class="table table-bordered" style="width:100%;">
                                <thead class="bg-aqua-gradient">
                                    <tr>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>TotalPrice</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                            <div class="form-group row">
                                <table class="pull-right" style="margin-right:20px;">
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>@Html.Label("Total")</td>
                                        <td>@Html.TextBox("TotalBill", null, new { @class = "form-control", @readonly = "readonly", @style = "width:120px;text-align:right;" })</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>@Html.Label("Discount")</td>
                                        <td>@Html.TextBox("Discount", null, new { @class = "form-control ", @style = "width:120px;text-align:right;" })</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>@Html.Label("Net Receivable")</td>
                                        <td>@Html.TextBox("NetReceivable", null, new { @class = "form-control", @readonly = "readonly", @style = "width:120px;text-align:right;" })</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>@Html.Label("Payment")</td>
                                        <td>@Html.TextBox("Payment", null, new { @class = "form-control ", @style = "width:120px;text-align:right;" })</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>@Html.Label("Change")</td>
                                        <td>@Html.TextBox("Change", null, new { @class = "form-control", @readonly = "readonly", @style = "width:120px;text-align:right;" })</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td><input type="submit" id="btnSave" class="btn btn-block btn-primary" value="Save" onclick="SubmitData(this, event);" /></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }



</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>

        //variables....
        var total = 0;
        var discount = 0;
        var nr = 0;
        var payment = 0;
        var change = 0;


        $(document).ready(function () {
            $("#TotalBill").val(0);
            $("#Discount").val(0);
            $("#NetReceivable").val(0);
            $("#Payment").val(0);
            $("#Change").val(0);
            $("#btnSave").hide();
        });


        //auto customer
        $(".autoPhone").autocomplete({

            source: '@Url.Action("getPhonenumberSupplier", "Common")'

        });

        //customer
        $("#SupplierPhone").keyup(function () {

            $.ajax({
                type: "post",
                url: "/Common/GetSupplier",
                data: { id: $('#SupplierPhone').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    $("#SupplierName").val(data.Name);
                    $.ajax({
                        type: "post",
                        url: "/Common/GetSupplierOrder",
                        data: { id: $('#SupplierPhone').val() },
                        datatype: "json",
                        traditional: true,
                        success: function (data) {
                            var my_orders = $("#OrderList");
                            my_orders.empty();
                            my_orders.append('<li><a style="color:red;">Previous ' + data.length + ' Orders Found !</a></li>')
                            $.each(data, function (i) {

                                my_orders.append('<li><a  target="_blank" href="/purchase/OrderDetails/' + data[i].Value + '">Order Number: ' + data[i].Text + '</a></li>');
                            });
                        }
                    });
                }
            });
        });



        $("#Product").change(function () {

            $.ajax({
                type: "post",
                url: "/Common/GetProductPurchasePrice",
                data: { id: $('#Product').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    $("#Price").val(data);
                    var quantity = $("#Quantity").val();
                    $("#TotalPrice").val(quantity * data);

                }
            });

        });

        $('#Quantity').on('input', function () {
            var QTY = $("#Quantity").val();
            var Price = $("#Price").val();
            $("#TotalPrice").val(QTY * Price);
        });

        $("#addItem").click(function () {

            if ($("#SupplierPhone").val() == "") {
                toastr.error('Please select Supplier', 'Required');
                $("#SupplierPhone").focus();

            } else if ($("#Product").val() == "") {
                toastr.error('Please select product', 'Required');
                $("#Product").select2('open');

            } else if ($("#Quantity").val() == "") {
                toastr.error('Please input Quantity', 'Required');
                $("#Quantity").focus();

            } else {
                // $("#Customer").prop("disabled", true);
                var product = { productName: $("#Product option:selected").text(), productId: $("#Product").val(), qty: $("#Quantity").val(), price: $("#Price").val(), totalprice: $("#TotalPrice").val() };
                var newRow = $('<tr><td> <input type="hidden" name="productId" value="' + product.productId + '">'
                    + '<label>' + product.productName  + '</label></td> '
                    + '<td><input type="hidden" name="productPrice" value="' + product.price + '"> <label >' + product.price + '</label></td>'
                    + '<td> <input type="hidden" name="productQty" value="' + product.qty + '"><label>' + product.qty + '</label></td>'
                    + '<td> <input type="hidden" name="productTotalPrice" value="' + product.totalprice + '"> <label>' + product.totalprice + '</label></td>'
                    + '<td> <button class="fa fa-close btn-danger" onclick="DeleteItem($(this).parent().parent().remove(), ' + product.totalprice + ')"></button> </td></tr>');
                $("#ItemTable").append(newRow);


                total += parseFloat(product.totalprice);
                calc();

                //reset values.......................
                $("#Product").select2('val', 'All');
                $("#Quantity").val('1');
                $("#Price").val('0');
                $("#TotalPrice").val('0');

            }
        });


        function DeleteItem(a, TotalPrice) {
            total = total - TotalPrice;
            calc();
        }

        function calc() {
            $("#TotalBill").val(total);
            discount = parseFloat($("#Discount").val());
            nr = total - discount;
            $("#NetReceivable").val(nr);

            if (nr > 0) {
                $("#btnSave").show();
            }
            else {
                $("#btnSave").hide();
            }

            payment = $("#Payment").val();
            change = payment - nr;
            if (change < 0) {
                change = 0;
            }

            $("#Change").val(change);

        }


        $('#Discount').focus(function () {
            if (this.value == 0) {
                $(this).val("");
            }
        }).blur(function () {
            if (this.value == "") {
                $(this).val(0);
            }
            calc();
            });

        $('#Payment').focus(function () {
            if (this.value == 0) {
                $(this).val("");
            }
        }).blur(function () {
            if (this.value == "") {
                $(this).val(0);
            }
            calc();
        });


        function SubmitData(ctl, event) {
            event.preventDefault();
            if ($("#SubmitForm").valid() == true) {
                swal({
                    title: "Do you want to save it?",
                    text: "Please check Information before Submiting!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Save",
                    cancelButtonText: "Cancel",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                    function (isConfirm) {
                        if (isConfirm) {

                            $("#SubmitForm").submit();

                        } else {
                            swal("Cancelled", "You have Cancelled Form Submission!", "error");
                        }
                    });
            }

        }


    </script>
}

Shop/Web/Views/Purchase/Index.cshtml
@model IEnumerable<Web.Models.Purchase>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Purchase List</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Purchase")">Purchase</a>
            </li>
            <li class="active">
                <strong>List</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2" style="margin-top:10px;">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="100">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Name</th>
                                <th data-hide="all"></th>
                                <th>Total Amount</th>
                                <th>Discount</th>
                                <th>Paid Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.PurchaseDate.ToShortDateString()
                                    </td>
                                    <td>
                                        @item.Supplier.Name<br /> (@item.Supplier.Phone)
                                    </td>
                                    <td>
                                        <table class="table table-bordered">
                                            <tr>
                                                <th>Name</th>
                                                <th>Qty</th>
                                                <th>Price</th>
                                            </tr>
                                            @foreach (var product in item.PurchaseItems)
                                            {
                                                <tr>
                                                    <td>@product.Product.Name</td>
                                                    <td>@product.QTY</td>
                                                    <td>@product.Price</td>
                                                </tr>
                                            }
                                        </table>
                                    </td>
                                    <td>@item.TotalAmount</td>
                                    <td>@item.Discount</td>
                                    <td>@item.PaidAmount</td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>